Add change.org case
elixir-lang/elixir-lang.github.com pull request #1463
Opened 2020-10-26 17:45 UTC by josevalim

![Screenshot_2020-10-26 Delivering social change with Elixir at Change org](https://user-images.githubusercontent.com/9582/97208455-6f62c800-17bb-11eb-9145-2299e5363bf1.png)

2020-10-26 20:08 UTC, ericmj approved these changes

2020-10-26 20:14 UTC, eksperimental requested changes

2020-10-26 20:14 UTC, eksperimental commented on _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
> +Around four months in, they put the new system in production. While Change.org has dozens of different email templates, the initial deployment handled a single and straight-forward case: password rec
```suggestion
After about four months, they put the new system in production. While Change.org has dozens of different email templates, the initial deployment handled a single and straight-forward case: password recovery.
```

I am not familiar with this "months in" expression.

2020-10-26 20:14 UTC, eksperimental commented on _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
> +The back-pressure provided by the [GenStage](https://github.com/elixir-lang/gen_stage/) library played a crucial role in the system’s performance.  Since those applications fetch events from message
```suggestion
The back-pressure provided by the [GenStage](https://github.com/elixir-lang/gen_stage) library played a crucial role in the system’s performance.  Since those applications fetch events from message queues, process them, and submit them into third-party services, they must avoid overloading any part of the stack. GenStage addresses this by allowing the different components, called stages in the library terminology, to communicate how much data they can handle right now. For example, if sending messages to the MTA is slower than usual, the system will naturally get fewer events from the queue.
```

2020-10-26 20:14 UTC, eksperimental commented on _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
> +Another essential feature of the system is to work in batches. Receiving and sending data is more efficient and cost-effective if you can do it in groups instead of one-by-one. John has given [a pres
```suggestion
Another essential feature of the system is to work in batches. Receiving and sending data is more efficient and cost-effective if you can do it in groups instead of one-by-one. John has given [a presentation at ElixirConf Europe sharing the lessons learned from their first trillion messages](https://www.youtube.com/watch?v=t46L9RKmlNo).
```

2020-10-26 20:14 UTC, eksperimental commented on _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
> +The activity on Change.org has grown considerably over the last year too. The systems have coped just fine. Justin remarks: "everything has been working so well that some of those services are not re
```suggestion
The activity on Change.org has grown considerably over the last year as well. The systems have coped just fine. Justin remarks: "everything has been working so well that some of those services are not really on our minds."
```

2020-10-26 20:14 UTC, eksperimental commented on _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
> +The team has also grown to 10 Elixir developers thanks to the multiple training and communities of practice they have organized internally. Change.org is also looking for Elixir backend engineers, as
```suggestion
The team has also grown to ten Elixir developers thanks to the multiple training and communities of practice they have organized internally. Change.org is also looking for Elixir backend engineers, as they aim to bring experience and diversity to their group. Interested developers can [learn more about these opportunities on their website](https://www.change.org/careers).
```

2020-10-26 20:19 UTC, josevalim commented on _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
> +When they started the project, none of the original team members had prior experience with Elixir. Only Justin Almeida, who joined six months in, had used Elixir before.
When the project had been running by 6 months. :)

2020-10-26 20:19 UTC, josevalim commented on _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
> +When they started the project, none of the original team members had prior experience with Elixir. Only Justin Almeida, who joined six months in, had used Elixir before.
```suggestion
When they started the project, none of the original team members had prior experience with Elixir. Only Justin Almeida, who joined when the project had been running by six months, had used Elixir before.
```

2020-10-26 20:22 UTC, josevalim commented on _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
> +The activity on Change.org has grown considerably over the last year too. The systems have coped just fine. Justin remarks: "everything has been working so well that some of those services are not re
Why? :)

2020-10-26 20:23 UTC, eksperimental commented on _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
> +When they started the project, none of the original team members had prior experience with Elixir. Only Justin Almeida, who joined six months in, had used Elixir before.
> When the project had been running by 6 months. :)

Then I would put it this way: "Only Justin Almeida, who joined in six months later, had used Elixir before."

2020-10-26 20:26 UTC, eksperimental commented on _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
> +The activity on Change.org has grown considerably over the last year too. The systems have coped just fine. Justin remarks: "everything has been working so well that some of those services are not re
It reads better IMO. While both expressions are equivalent, "as well" is considered to be more formal than "too".

2020-10-26 21:30 UTC, josevalim commented on _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
> +The activity on Change.org has grown considerably over the last year too. The systems have coped just fine. Justin remarks: "everything has been working so well that some of those services are not re
Keeping it as is then, unless there is a explicit reference that says we should prefer one or the other, although formiality is not strict here. Thanks.

2020-10-26 21:49 UTC, fertapric approved these changes

2020-10-27 03:54 UTC, eksperimental commented on _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
> +When they started the project, none of the original team members had prior experience with Elixir. Only Justin Almeida, who joined six months in, had used Elixir before.
running **for** six months?

2020-10-27 15:53 UTC, merged